// Banco de dados 2 dos produtos

const produtosTenis = [
  {
    id: 1,
    img: "./src/produtos-tenis/1.jpg",
    nameItem: "Antivibrador - Head",
    description: "Antivibrador Head Pro Damp",
    value: 59,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 2,
    img: "./src/produtos-tenis/2.jpg",
    nameItem: "Antivibrador - Wilson",
    description: "Antivibrador Wilson Pro Feel",
    value: 49,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 3,
    img: "./src/produtos-tenis/3.jpg",
    nameItem: "Raquete de Tênis - Babolat",
    description: "Raquete de Tênis New Pure Aero Rafa Babolat",
    value: 1849,
    addCart: "Adicionar ao carrinho",
    tag: ["Raquetes"],
  },
  {
    id: 4,
    img: "./src/produtos-tenis/4.jpg",
    nameItem: "Raquete de Tênis - Head",
    description: "Raquete de Tênis Head 360+ Extreme MP + Bola e Corda",
    value: 1999,
    addCart: "Adicionar ao carrinho",
    tag: ["Raquetes"],
  },
  {
    id: 5, // VER
    img: "./src/produtos-tenis/5.jpg",
    nameItem: "Raquete de Tênis - Wilson",
    description: "Raquete de Tênis Wilson Pro Staff Precision XL 110",
    value: 299,
    addCart: "Adicionar ao carrinho",
    tag: ["Raquetes"],
  },
  {
    id: 6,
    img: "./src/produtos-tenis/6.jpg",
    nameItem: "Raquete de Tênis - Wilson",
    description:
      "Raquete de Tenis Wilson Ultra Minions 100 + Brinde Bola e Corda",
    value: 1599,
    addCart: "Adicionar ao carrinho",
    tag: ["Raquetes"],
  },
  {
    id: 7,
    img: "./src/produtos-tenis/7.jpg",
    nameItem: "Munhequeira - Adiddas",
    description:
      "Oferecer total absorção do suor e máxima precisão nos movimentos",
    value: 89,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 8,
    img: "./src/produtos-tenis/8.jpg",
    nameItem: "Munhequeira - Nike",
    description: "Munhequeira Nike Swoosh Pequena - Branca",
    value: 99,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 9,
    img: "./src/produtos-tenis/9.jpg",
    nameItem: "Bolas - Wilson",
    description: "Bola de Tênis Wilson US Open Extra Duty",
    value: 79,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 10,
    img: "./src/produtos-tenis/10.jpg",
    nameItem: "Cesto Bolas - Ballport",
    description: "Cesto de Bola Plástico BallPort Para 80 Bolas Tourna Unique",
    value: 689,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
  },
  {
    id: 11,
    img: "./src/produtos-tenis/11.jpg",
    nameItem: "Raqueteira - Head",
    description: "Raqueteira Head Elite Combi 6R Preta e Branca",
    value: 489,
    addCart: "Adicionar ao carrinho",
    tag: ["Bolsas"],
  },
  {
    id: 12,
    img: "./src/produtos-tenis/12.jpg",
    nameItem: "Raqueteira - Wilson",
    description: "Raqueteira Super Tour 15 Pack",
    value: 1799,
    addCart: "Adicionar ao carrinho",
    tag: ["Bolsas"],
  },
  {
    id: 13,
    img: "./src/produtos-tenis/13.jpg",
    nameItem: "Raqueteira - Head",
    description: "Raqueteira Head Backhand",
    value: 459,
    addCart: "Adicionar ao carrinho",
    tag: ["Bolsas"],
  },
  {
    id: 14,
    img: "./src/produtos-tenis/14.jpg",
    nameItem: "Raqueteira - Wilson",
    description: "Raqueteira Wilson Super Tour 15Pk Pro Staff Black",
    value: 1849,
    addCart: "Adicionar ao carrinho",
    tag: ["Bolsas"],
  },
  {
    id: 15,
    img: "./src/produtos-tenis/15.jpg",
    nameItem: "Raqueteira - Head",
    description: "Raqueteira Head Elite Combi 6R",
    value: 399,
    addCart: "Adicionar ao carrinho",
    tag: ["Bolsas"],
  },
  {
    id: 16,
    img: "./src/produtos-tenis/16.jpg",
    nameItem: "Raqueteira - Babolat",
    description: "Raqueteira Babolat X6 Pure Aero Preta",
    value: 1099,
    addCart: "Adicionar ao carrinho",
    tag: ["Bolsas"],
  },
  {
    id: 17,
    img: "./src/produtos-tenis/17.jpg",
    nameItem: "Raquete de Tênis - Head",
    description: "Raquete de Tênis TI Radical Elite Modelo 2022",
    value: 619,
    addCart: "Adicionar ao carrinho",
    tag: ["Raquetes"],
  },
  {
    id: 18,
    img: "./src/produtos-tenis/18.jpg",
    nameItem: "Raquete de Tênis - Babolat",
    description: "Raquete De Tenis Babolat Pure Aero 2021",
    value: 1629,
    addCart: "Adicionar ao carrinho",
    tag: ["Raquetes"],
  },
  {
    id: 19,
    img: "./src/produtos-tenis/19.jpg",
    nameItem: "Raquete de Tênis - Wilson",
    description: "Raquete de Tênis Wilson Blade Feel 100",
    value: 719,
    addCart: "Adicionar ao carrinho",
    tag: ["Raquetes"],
  },
];

export default produtosTenis;
